### ISSUE TITLE
Reaname the module

### ISSUE THREAD

**Issue by onicollet** [Tar-Abg/kendoInWebpack#2]
Can you rename your module Tar-Abg/kendoGridModule or at least kendoGridModule not module2

https://github.com/Tar-Abg/kendoInWebpack/blob/cc4692f9ba5305398155e1f066a45e10031d6dc3/package.json#L17

**Comment by Tar-Abg** [comment]
`"kendoGridModule": "github:Tar-Abg/kendoGridModule",`
